/**
 * This file implements a catch-all route that renders the user-facing pages
 * generated by Puck. For any route visited (with exception of other hardcoded
 * pages in /app), it will check your database (via `getPage`) for a Puck page
 * and render it using <Render>.
 *
 * All routes produced by this page are statically rendered using incremental
 * static site generation. After the first visit, the page will be cached as
 * a static file. Subsequent visits will receive the cache. Publishing a page
 * will invalidate the cache as the page is written in /api/puck/route.ts
 */

import type { Metadata } from "next";
import type {
  RootProps,
  SeoImageProps,
  SeoProps,
} from "@/puck/components/root";
import { Client } from "./client";
import { getPage } from "../../lib/get-page";
import { notFound } from "next/navigation";

const hasValue = (value?: string) => Boolean(value?.trim());

const getResolvedValue = (...values: Array<string | undefined>) =>
  values.find(hasValue);

const getResolvedImage = (
  primary?: Partial<SeoImageProps>,
  fallback?: Partial<SeoImageProps>
) => {
  const src = getResolvedValue(primary?.src, fallback?.src);

  if (!src) {
    return undefined;
  }

  const alt = getResolvedValue(primary?.alt, fallback?.alt);

  return {
    url: src,
    ...(alt ? { alt } : {}),
  };
};

const getOpenGraphMetadata = (
  seo?: Partial<SeoProps>,
  fallbackTitle?: string
): Metadata["openGraph"] => {
  const openGraph = seo?.openGraph;
  const image = getResolvedImage(openGraph?.image, seo?.image);
  const title = getResolvedValue(openGraph?.title, seo?.title, fallbackTitle);
  const description = getResolvedValue(openGraph?.description, seo?.description);

  if (!title && !description && !image) {
    return undefined;
  }

  return {
    ...(title ? { title } : {}),
    ...(description ? { description } : {}),
    ...(image ? { images: [image] } : {}),
  };
};

const getTwitterMetadata = (
  seo?: Partial<SeoProps>,
  fallbackTitle?: string
): Metadata["twitter"] => {
  const twitter = seo?.twitter;
  const image = getResolvedImage(twitter?.image, seo?.image);
  const title = getResolvedValue(twitter?.title, seo?.title, fallbackTitle);
  const description = getResolvedValue(twitter?.description, seo?.description);
  const card = twitter?.card;

  if (!title && !description && !image && !card) {
    return undefined;
  }

  return {
    ...(card ? { card } : {}),
    ...(title ? { title } : {}),
    ...(description ? { description } : {}),
    ...(image ? { images: [image] } : {}),
  };
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ puckPath: string[] }>;
}): Promise<Metadata> {
  const { puckPath = [] } = await params;
  const path = `/${puckPath.join("/")}`;
  const page = getPage(path);
  const rootProps = page?.root.props as Partial<RootProps> | undefined;
  const seo = rootProps?.seo as Partial<SeoProps> | undefined;
  const title = getResolvedValue(seo?.title, rootProps?.title);
  const description = getResolvedValue(seo?.description);
  const canonicalUrl = getResolvedValue(seo?.canonicalUrl);
  const openGraph = getOpenGraphMetadata(seo, rootProps?.title);
  const twitter = getTwitterMetadata(seo, rootProps?.title);

  return {
    ...(title ? { title } : {}),
    ...(description ? { description } : {}),
    ...(canonicalUrl
      ? {
          alternates: {
            canonical: canonicalUrl,
          },
        }
      : {}),
    ...(openGraph ? { openGraph } : {}),
    ...(twitter ? { twitter } : {}),
  };
}

export default async function Page({
  params,
}: {
  params: Promise<{ puckPath: string[] }>;
}) {
  const { puckPath = [] } = await params;
  const path = `/${puckPath.join("/")}`;
  const data = getPage(path);

  if (!data) {
    return notFound();
  }

  return <Client data={data} />;
}

// Force Next.js to produce static pages: https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamic
// Delete this if you need dynamic rendering, such as access to headers or cookies
export const dynamic = "force-static";
