export const THEME_VARIABLES = {
  font: {
    family: "--default-font-family",
  },
  units: {
    radius: "--radius",
  },
  palette: {
    background: "--background",
    foreground: "--foreground",
    card: "--card",
    cardForeground: "--card-foreground",
    popover: "--popover",
    popoverForeground: "--popover-foreground",
    primary: "--primary",
    primaryForeground: "--primary-foreground",
    secondary: "--secondary",
    secondaryForeground: "--secondary-foreground",
    muted: "--muted",
    mutedForeground: "--muted-foreground",
    accent: "--accent",
    accentForeground: "--accent-foreground",
    destructive: "--destructive",
    destructiveForeground: "--destructive-foreground",
    border: "--border",
    input: "--input",
    ring: "--ring",
  },
};

export const FONT_FAMILIES = [
  "Archivo",
  "Arial",
  "Brush Script MT",
  "Courier New",
  "Garamond",
  "Georgia",
  "Google Sans Flex",
  "Helvetica",
  "Inconsolata",
  "Inter",
  "Libre Baskerville",
  "Lora",
  "Merriweather",
  "Montserrat",
  "Noto Sans",
  "Open Sans",
  "Oswald",
  "Playfair Display",
  "Playwrite NO",
  "Poppins",
  "Roboto",
  "Science Gothic",
  "Source Code Pro",
  "Tahoma",
  "Times New Roman",
  "Trebuchet MS",
  "Verdana",
];
